### ISSUE TITLE
Error installing via composer

### ISSUE THREAD

**Issue by mtjweb** [fooman/sameorderinvoicenumber-implementation-m2#3]
I'mgetting the following error when installing via Composer:

`Higher matching version 104.1.0 of fooman/sameorderinvoicenumber-implementation-m2 was found in public repository packagist.org
                               than 104.0.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,
                               please investigate and update package requirement to match the version from the private repository
`

**Comment by fooman** [comment]
This is unfortunately due to Magento's composer plugin, essentially forcing any version to be released on Marketplace first (or exclusively). Since our publishing process to Marketplace is manual but to Packagist is automated there will always be a window where the version number on packagist will be ahead.

Closing this as this is not something that we can easily change from our end. You may want to follow this issue https://github.com/magento/composer-dependency-version-audit-plugin/issues/6 to see what Adobe's plans are.
